version: '3'
services:
  consul:
    image: hashicorp/consul
    ports:
      - '8500:8500'

  service-a:
    build: ./service-a
    ports:
      - '3001:3001'
    environment:
      - SERVICE_NAME=service-a

  service-b:
    build: ./service-b
    ports:
      - '3002:3002'
    environment:
      - SERVICE_NAME=service-b

  service-c:
    build: ./service-c
    ports:
      - '3003:3003'
    environment:
      - SERVICE_NAME=service-c

  gateway:
    build: ./gateway
    ports:
      - '8080:8080'
    depends_on:
      - service-a
      - service-b
      - service-c

