$schema: "http://express-gateway.io/schemas/system.schema.json"
$id: "https://express-gateway.io/schemas/system.config.json"

admin:
  port: 9876
  host: localhost

db:
  redis:
    namespace: eg
    url: redis://redis:6379

logger:
  level: info
